### ISSUE TITLE
Failed to download images

### ISSUE THREAD

**Issue by prnr** [SysCV/nutsh#9]
![화면 캡처 2023-11-09 183427](https://github.com/SysCV/nutsh/assets/22967869/c7bbb315-e3f8-455e-9b27-7cd6f0a561cd)

I'm trying to connect an image file to nutsh that I deployed to aws using the synology web service. If you enter the image file address directly into the browser, it will be output normally, but no image will be output in nutsh. I don't know what the issue is, is it a firewall issue with aws?

**Comment by prnr** [comment]
![image](https://github.com/SysCV/nutsh/assets/22967869/067a8c87-d1ba-45a9-b8e1-e0337ea7a9de)
The console error message is displayed as above.

**Comment by hxhxhx88** [comment]
Hi @prnr . Could you export your project, or paste some of your image urls, to me, so I can have a look? My preliminary thought is that it is due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) constraints. Usually it need to be resolved on the server side, namely by the owner of `greon.synology.me`, but I would like to see if there is anything I can do on the nutsh side.

BTW I tried to open [http://greon.synology.me/web_images/sk_images/1_1.png](http://greon.synology.me/web_images/sk_images/1_1.png) but failed. Is it a temporary address?

**Comment by prnr** [comment]
> Hi @prnr . Could you export your project, or paste some of your image urls, to me, so I can have a look? My preliminary thought is that it is due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) constraints. Usually it need to be resolved on the server side, namely by the owner of `greon.synology.me`, but I would like to see if there is anything I can do on the nutsh side.
> 
> BTW I tried to open http://greon.synology.me/web_images/sk_images/1_1.png but failed. Is it a temporary address?

Oh, maybe it's because the synology nas firewall has blocked foreign access (except Korea and Japan). I just gave permission for that function (webstation, port 80/8080), but is the image still not accessible?
[t1.json](https://github.com/SysCV/nutsh/files/13315767/t1.json)

**Comment by hxhxhx88** [comment]
@prnr Hi! The image and the json is now fine. I'll give it a look and reach you back soon.

**Comment by hxhxhx88** [comment]
@prnr Hi! I have checked the image, and indeed it is due to so-called [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

In short, it is a safety mechanism to prevent data on a server([origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin)) A to be accessed by another server(origin) B, namely cross-origin. Apparently your Synology NAS server applies this policy, thus your nutsh app can not access your image without further configuration to allow so. (Since opening the image directly from the browser is not crossing origins, so you can see the image.)

One solution is to configure your synology server to add the following HTTP header to the response serving images:
```
Access-Control-Allow-Origin "*"
```
which means "allowing all origins to access". Surely your can change the `*` to something more restritive.

I haven't dealt with synology nas so don't know how to configure. I did some google search for your and am not sure if the following link helps:
- [Setting up CORS on Synology Web Station](https://www.reddit.com/r/synology/comments/17ldnop/setting_up_cors_on_synology_web_station_solved/)

Hope this helps and feel free to let me know if you still run into troubles:)

**Comment by prnr** [comment]
> @prnr Hi! I have checked the image, and indeed it is due to so-called [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
> 
> In short, it is a safety mechanism to prevent data on a server([origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin)) A to be accessed by another server(origin) B, namely cross-origin. Apparently your Synology NAS server applies this policy, thus your nutsh app can not access your image without further configuration to allow so. (Since opening the image directly from the browser is not crossing origins, so you can see the image.)
> 
> One solution is to configure your synology server to add the following HTTP header to the response serving images:
> 
> ```
> Access-Control-Allow-Origin "*"
> ```
> 
> which means "allowing all origins to access". Surely your can change the `*` to something more restritive.
> 
> I haven't dealt with synology nas so don't know how to configure. I did some google search for your and am not sure if the following link helps:
> 
> * [Setting up CORS on Synology Web Station](https://www.reddit.com/r/synology/comments/17ldnop/setting_up_cors_on_synology_web_station_solved/)
> 
> Hope this helps and feel free to let me know if you still run into troubles:)
![image](https://github.com/SysCV/nutsh/assets/22967869/eb32ebd4-dd12-48e5-86e8-c068a7142336)

The NAS is not my server, so I couldn't modify the settings. I uploaded the image to aws S3 and tried to access it the same way. This time I get an error message [The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.].

This issue seems to have needed https application (ec2 is http and s3 is https, so it seems like the problem occurred with NAS for the same reason). I uploaded it to s3 now and it is working normally. Thanks for helping me solve it!
